Vagrant.configure(2) do |config|
  
  # CONF HARDWARE
  config.vm.provider :virtualbox do |vb|
  	vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "1"]
  end

  config.vm.network :forwarded_port, guest: 80, host: 8080
  
  # CONF BOX METADATA
  config.vm.define "apache" do |confa|
    confa.vm.box = "centos/7"
  	confa.vm.hostname = "apache.example.vag"
  end

  # PROVISION
  config.vm.provision "shell", path: "Web_Server_Init.sh"
  config.vm.provision "file", source: "index.html", destination: "/var/www/html/www/index.html"
  config.vm.provision "file", source: "www.conf", destination: "/etc/httpd/conf.d/www.conf"
  config.vm.provision "shell", inline: "systemct restart httpd.service"
  config.vm.provision "shell", inline: "echo Provision successfull !"

end